name: Update IPTV Playlist

on:
  schedule:
    - cron: '*/55 * * * *'  # Runs every 55 minutes

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python to use

      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update script
        run: python update_m3u.py
